### ISSUE TITLE
Cache invalidation of source nodes with help of user

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#12]
We still need a way to allow the user help in cache invalidating source nodes. There was the idea to pass a custom cache validity checking function to @materialize. The problem of this approach is that there might be still user specific input needed which is available during wiring of tasks in the flow. So I am currently favoring the approach to add special @materialize tasks at the beginning which always run (i.e. lazy=true will do) and emit a CacheInfo(xxx) object which is used to compute the cache validity hash. It could look like this:
```python
@materialize(input_type=sa.Table, lazy=True)
def source_valid(landing_zone_schema: str):
    config = ConfigContext.get()
    store = config.store.table_store
    meta = sa.MetaData()
    meta.reflect(bind=store.engine, schema=landing_zone_schema)
    tbl = sa.Table("main_table", meta)
    last_timestamp = sa.select([sa.func.max(tbl.c.timestamp)]).fetchall()[0][0] 
    return CashInfo(last_timestamp)
```
The CacheInfo object can be passed on to other @materialize tasks creating a dependency chain by that.

It is even possible to pass multiple arguments to CacheInfo which all will be traversed and hashed with `deep_visit()`. And it is possible to pass SQLAlchemy tables to the output which effectively copies the tables into the stage where source_tables() task is part of:
```python
@materialize(input_type=sa.Table, lazy=True)
def source_tables(landing_zone_schema: str):
    config = ConfigContext.get()
    store = config.store.table_store
    meta = sa.MetaData()
    meta.reflect(bind=store.engine, schema=landing_zone_schema)
    last_timestamps = [sa.select([sa.func.max(tbl.c.timestamp)]).fetchall()[0][0] for tbl in meta.tables]
    return CashInfo(landing_zone_schema, last_timestamps, [tbl.name for tbl in meta.tables]), [Table(tbl) for meta.tables]
```

**Comment by windiana42** [comment]
@NMAC427 @EnchoMishinevQC  what do you think?

**Comment by NMAC427** [comment]
For comparison, this is the version I proposed:

```python
## Table Example
def get_meta(schema: str):
    config = ConfigContext.get()
    store = config.store.table_store
    meta = sa.MetaData()
    meta.reflect(bind=store.engine, schema=schema)
    return meta

def schema_cache(schema: str):
    meta = get_meta()
    last_timestamps = [sa.select([sa.func.max(tbl.c.timestamp)]).fetchall()[0][0] for tbl in meta.tables]
    return schema, last_timestamps, [tbl.name for tbl in meta.tables]

@materialize(cache=schema_cache)
def source_tables(landing_zone_schema: str):
    meta = get_meta()
    tables = [Table(tbl) for meta.tables]
    return tables


## File example
def md5_hash(path: str):
    with open(path, 'rb') as f:
        data = f.read()    
        return hashlib.md5(data).hexdigest()

@materialize(cache=partial(map, md5_hash))
def load_csvs(paths: list[str]):
    return [pd.read_csv(path) for path in paths]
```

Before a materializing function gets called, the corresponding cache function gets called with the same arguments. 
If no cache function is provided, the default one is used (which just hashes the arguments).
The return value of the cache function then is used to construct a cache key.
Only if this cache key has changed compared to the previous execution do we run the materializing function again.

In my opinion, this approach is a lot more elegant and powerful:
- The "should I run this piece of code or not" function doesn't get materialized to the database. Because it isn't directly part of the DAG, it also doesn't clutter up the flow definition of the visualization.
- It doesn't abuse the `lazy` argument (the behavior of lazy is a lot more complex than just indicating that a function should always be executed; it really should only ever be used with tables based on lazy queries).
- It makes reusing of common cache keys easier (e.g. you define once how to calculate the md5 hash of a file and then can reuse the same cache function in multiple locations).
- It makes it easier to visualize in a UI that a task was skipped because it's cache function was still valid.

To show that it is more powerful, let's look at the `load_csvs` example:
The cache key would stay the same even if you changed the paths.
As long as the contents of the files stay the same, the exact paths given to `load_csvs` wouldn't matter.
I don't see a way how the same behavior could be implemented using your proposed approach.

**Comment by QuantCo-mr-T** [comment]
@NMAC427 exactly the point that the cache function gets called with the same arguments as the materialized function drove me to the more explicit approach in terms of cache function declaration

**Comment by QuantCo-mr-T** [comment]
And I actually like the cache invalidation function being part of the graph since it may decide to trigger only the refresh of a sub-dag.
I admit, I am misusing the term @materialize if the function neither reads tables/blobs nor writes them. We might define a synonym annotation for this special case which might also make an optical difference in the dag visualization.

**Comment by QuantCo-mr-T** [comment]
```python
@materialize(cache=None) 
def load_csvs(paths: list[str]): 
  return CacheInfo(map(paths,hash_md5)),[pd.read_csv(path) for path in paths]
```
I even would claim this makes it easier to share state between performing load operations and Cache Invalidation Logic

**Comment by NMAC427** [comment]
> ```python
> ```python
> @materialize(cache=None) 
> def load_csvs(paths: list[str]): 
>   return CacheInfo(map(paths,hash_md5)),[pd.read_csv(path) for path in paths]
> ```

But this is not the behavior that we want. The intended goal is to read the csvs (or execute any other potentially expensive operations) *if and only if* we have determined that the function is going to produce a different output (in other words if any of the md5 hashes has changed).

**Comment by windiana42** [comment]
CC: @verticube

**Comment by windiana42** [comment]
> But this is not the behavior that we want. The intended goal is to read the csvs (or execute any other potentially expensive operations) if and only if we have determined that the function is going to produce a different output (in other words if any of the md5 hashes has changed).

The point was to show that this way you can also read the file once and deliver cache validity as well as table contents together in one go. I know the presented solution did not get rid of reading the files twice.

I still don't like that the cache function gets a list of parameters as they were declared on another function, but I can implement it that way for now and in fact it would be trivial to implement the CacheInfo solution at the same time. It would even be possible to ask for the last invocation CacheInfo as input parameter from the @materialize annotation which allows also to decide cache validity inside the function and thus not returning information which would be discarded anyways.
